# Generated by Django 4.0.4 on 2022-05-10 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '0001_initial'),
        ('cuenta', '0003_remove_cuenta_idtipodocumento_cuenta_idtipocuenta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nota Explicativa')),
                ('idasiento', models.IntegerField(verbose_name='Número de Asiento')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Importe +Debe -Haber)')),
                ('idcuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuenta.cuenta', verbose_name='Cuenta')),
                ('idestudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante', verbose_name='Estudiante')),
            ],
        ),
    ]
