# Generated by Django 4.0.4 on 2022-05-10 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipocuenta', '0001_initial'),
        ('estudiante', '0001_initial'),
        ('cuenta', '0002_cuenta_idestudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='idtipodocumento',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='idtipocuenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tipocuenta.tipocuenta', verbose_name='Grupo de Cuentas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='idestudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante', verbose_name='Estudiante'),
        ),
    ]
