# Generated by Django 4.0.4 on 2022-05-10 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipodocumento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(default='averiguar@elcorreo.com', max_length=200, verbose_name='Correo Electrónico')),
                ('numerodocumento', models.CharField(max_length=12, verbose_name='Nombre')),
                ('idtipodocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipodocumento.tipodocumento')),
            ],
        ),
    ]
